# -*- coding: utf-8 -*-
"""generate_visuals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_hU6OLRLooKVi29hBy6Xc3sfE3UDV5rB
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

# Load dataset
df = pd.read_csv("/content/AI_Lifecycle_Analyzer_Updated.csv")

# Create visuals directory if not exists
os.makedirs("visuals", exist_ok=True)

# Add engineered columns if not present
df['Impact_per_Year'] = df['Carbon_Footprint_kgCO2'] / df['Lifespan_Years']
df['Eco_Index'] = (df['Sustainability_Rating'] * 5) / (df['Carbon_Footprint_kgCO2'] + df['Waste_Generated_kg'])

sns.set(style="whitegrid")

# 1. Histogram - Carbon Footprint Distribution
plt.figure(figsize=(8, 5))
sns.histplot(df['Carbon_Footprint_kgCO2'], kde=True, color='skyblue')
plt.title("Distribution of Carbon Footprint")
plt.xlabel("Carbon Footprint (kgCO₂)")
plt.ylabel("Frequency")
plt.tight_layout()
plt.savefig("visuals/carbon_footprint_distribution.png")
plt.close()

# 2. Box Plot - Sustainability Rating by Product (using one-hot encoded column)
plt.figure(figsize=(10, 5))
sns.boxplot(x='Product_Name_Laptop', y='Sustainability_Rating', data=df) # Removed palette argument
plt.title("Sustainability Rating by Product (Laptop)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("visuals/sustainability_rating_boxplot.png")
plt.close()

# 3. Bar Chart - Average Carbon Footprint (removed grouping by Product_Name)
avg_impact = df['Carbon_Footprint_kgCO2'].mean() # Removed grouping
plt.figure(figsize=(8, 6))
plt.barh("Overall Average", avg_impact, color='salmon') # Changed to a single bar for overall average
plt.title("Average Carbon Footprint")
plt.xlabel("kg CO₂")
plt.tight_layout()
plt.savefig("visuals/avg_carbon_footprint_overall.png") # Changed filename
plt.close()

# 4. Scatter Plot - Weight vs. Carbon Footprint (removed hue by Product_Name)
plt.figure(figsize=(8, 5))
sns.scatterplot(x='Weight_kg', y='Carbon_Footprint_kgCO2', data=df) # Removed hue='Product_Name'
plt.title("Weight vs. Carbon Footprint")
plt.tight_layout()
plt.savefig("visuals/weight_vs_carbon_scatter.png")
plt.close()

# 5. Correlation Heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(df.select_dtypes(include='number').corr(), annot=True, cmap='coolwarm', linewidths=0.5)
plt.title("Correlation Heatmap")
plt.tight_layout()
plt.savefig("visuals/correlation_heatmap.png")
plt.close()

# 6. Pie Chart - Distribution of Disposal Methods
plt.figure(figsize=(6, 6))
disposal_counts = df[['Disposal_Method_Landfill', 'Disposal_Method_Recycled', 'Disposal_Method_Reused']].sum()
plt.pie(disposal_counts, labels=disposal_counts.index, autopct='%1.1f%%', startangle=90, wedgeprops=dict(width=0.4))
plt.title("Distribution of Disposal Methods")
plt.ylabel("")
plt.tight_layout()
plt.savefig("visuals/disposal_method_pie.png")
plt.close()

# 7. Bar Chart - Average Eco Index (removed grouping by Product_Name)
eco_index_avg = df['Eco_Index'].mean() # Removed grouping
plt.figure(figsize=(8, 6))
plt.bar("Overall Average", eco_index_avg, color='green') # Changed to a single bar for overall average
plt.title("Average Eco Index Overall") # Changed title
plt.ylabel("Eco Index")
plt.tight_layout()
plt.savefig("visuals/eco_index_overall.png") # Changed filename
plt.close()

print("✅ All visualizations saved in the 'visuals/' folder.")